### 실제 파일 업로드
POST http://localhost:3000/file-upload
Content-Type: multipart/form-data; boundary=test-file-upload

--test-file-upload
Content-Disposition: form-data; name="file"; filename="test.txt"


# 여기에 텍스트 파일의 내용을 넣을 수 있다.
# --test-file-upload--

< test.txt
--test-file-upload--

### 사진 업로드
POST http://localhost:3000/file-upload
Content-Type: multipart/form-data; boundary=image-file-upload

--image-file-upload
Content-Disposition: form-data; name="file"; filename="hug.jpg"
Content-Type: image/jpeg

< hug.jpg
--image-file-upload--