#
@server = http://localhost:3000

###
GET {{server}}/person
###
POST {{server}}/person
Content-Type: application/json

{
    "name" : "mingyu",
    "age" : 26,
    "email" : "threebr123@naver.com"
}

###
GET {{server}}/person/threebr123@naver.com

###
PUT {{server}}/person.threebr123@naver.com
Content-Type: application/json

{
    "age" : 32
}

###
DELETE {{server}}/person/threebr123@naver.com